### ISSUE TITLE
Question: Java-Javascript state replication

### ISSUE THREAD

**Issue by Katharsas** [replicant4j/replicant#25]
Hello,

sorry if this issue tracker is the wrong place for my question (feel free to close).
Im currently looking for a library that allows me to replicate/synchronize state between a Java server and Javascript browser clients.

I have looked into Frameworks like GWT and Vaadin but i don't want to write my clients in Java. I just want to replicate some state between the server and the clients and then render the UI myself with Javascript.

This looks like it could be the solution, however using GWT just to get the state replication seems overkill. I just need the client side of this replication library in Javascript form.
Maybe i can just extract that from GWT somehow, basically using GWT only to compile a client for this library and then call that from my own Javascript code?
Or maybe there exists a Javascript client for this library already somehwere?

**Comment by realityforge** [comment]
Unfortunately, the library is relatively strongly tied to GWT (and/or [j2cl](https://github.com/google/j2cl)). The library has relatively strong requirements on how you write your server and structure your database which makes it difficult to build into other systems without the other infrastructure of which there is no documentation.

While we use it for "business applications", the library traces it's existence back to a distributed virtual environment / networked game architecture research and thus is very unlikely to be of much use in other contexts ;)

Sorry about that.

One day I may get around to bringing in other components and writing documentation but until then this is probably not the library you are looking for.

Good luck!
